app:
  config:
    marker: ATLAS_CONFIG_LOADED

spring:
  data:
    mongodb:
      uri: mongodb+srv://pvaisakh2002_db_user:4CMD2IhjAXnkuKU5@cluster0.rjzz0lr.mongodb.net/journaldb?appName=Cluster0
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /app
# Debug logging
